[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200